import type { SourceDefinition } from "../lib/sourceAdmission.js";
import type { Category, Locale, MediaType, Region, SourceSection } from "../types";

interface ExpandedSectionInput {
  label: string;
  url: string;
  primaryCategory: Category;
  categories: Category[];
  searchTerms: string[];
  /** Public RSS/Atom discovery endpoint; never used for article host scoping. */
  feedUrl?: string;
}

interface ExpandedSourceInput {
  sourceId: string;
  name: string;
  countryOrRegion: Region;
  language: Locale;
  mediaType: MediaType;
  defaultWeight: number;
  credibility: number;
  requireChinese: boolean;
  sections: ExpandedSectionInput[];
}

function toSection(input: ExpandedSectionInput, requireChinese: boolean): SourceSection {
  return {
    label: input.label,
    url: input.url,
    ...(input.feedUrl ? { feedUrl: input.feedUrl } : {}),
    primaryCategory: input.primaryCategory,
    categories: input.categories,
    searchTerms: input.searchTerms,
    searchSources: requireChinese ? ["news"] : ["web", "news"],
    requireChinese,
  };
}

function defineExpandedSource(input: ExpandedSourceInput): SourceDefinition {
  return {
    source_id: input.sourceId,
    name: input.name,
    countryOrRegion: input.countryOrRegion,
    language: input.language,
    mediaType: input.mediaType,
    defaultWeight: input.defaultWeight,
    credibility: input.credibility,
    mayHavePaywall: false,
    enabled: true,
    sections: input.sections.map((section) => toSection(section, input.requireChinese)),
  };
}

/**
 * User-approved non-X publisher expansion. Every entry is enabled and is merged
 * into the curated catalog by `sources.ts` through `defineApprovedSource`, so
 * `allowedHosts` continues to be derived exclusively from reader section URLs.
 */
export const expandedSourceDefinitions: SourceDefinition[] = [
  defineExpandedSource({
    sourceId: "deepseek",
    name: "DeepSeek 深度求索",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "official",
    defaultWeight: 0.86,
    credibility: 86,
    requireChinese: true,
    sections: [
      {
        label: "官方发布",
        url: "https://www.deepseek.com/",
        primaryCategory: "ai",
        categories: ["ai", "technology"],
        searchTerms: ["DeepSeek 官方 模型", "DeepSeek 深度求索 发布"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "qwen",
    name: "通义千问 Qwen",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "official",
    defaultWeight: 0.84,
    credibility: 84,
    requireChinese: true,
    sections: [
      {
        label: "官方发布",
        url: "https://qwenlm.github.io/",
        primaryCategory: "ai",
        categories: ["ai", "technology"],
        searchTerms: ["通义千问 Qwen 模型", "Qwen 官方 发布"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "z-ai",
    name: "智谱 Z.ai",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "official",
    defaultWeight: 0.82,
    credibility: 82,
    requireChinese: true,
    sections: [
      {
        label: "官方发布",
        url: "https://z.ai/",
        primaryCategory: "ai",
        categories: ["ai", "technology"],
        searchTerms: ["智谱 GLM 发布", "Z.ai 智谱 模型"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "arxiv",
    name: "arXiv 论文预印本",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.78,
    credibility: 80,
    requireChinese: false,
    sections: [
      {
        label: "cs.AI",
        url: "https://arxiv.org/",
        primaryCategory: "ai",
        categories: ["ai", "science", "technology"],
        searchTerms: ["arXiv cs.AI latest", "arXiv artificial intelligence papers"],
        feedUrl: "https://rss.arxiv.org/rss/cs.AI",
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "ithome",
    name: "IT之家",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "technology",
    defaultWeight: 0.72,
    credibility: 68,
    requireChinese: true,
    sections: [
      {
        label: "科技",
        url: "https://www.ithome.com/",
        primaryCategory: "technology",
        categories: ["technology", "ai"],
        searchTerms: ["IT之家 科技", "IT之家 数码 互联网"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "leiphone",
    name: "雷峰网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "technology",
    defaultWeight: 0.72,
    credibility: 68,
    requireChinese: true,
    sections: [
      {
        label: "科技",
        url: "https://www.leiphone.com/",
        primaryCategory: "technology",
        categories: ["technology", "ai"],
        searchTerms: ["雷峰网 科技", "雷峰网 AI 智能"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "ifanr",
    name: "爱范儿",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "technology",
    defaultWeight: 0.7,
    credibility: 66,
    requireChinese: true,
    sections: [
      {
        label: "科技",
        url: "https://www.ifanr.com/",
        primaryCategory: "technology",
        categories: ["technology", "ai"],
        searchTerms: ["爱范儿 科技", "爱范儿 数码 产品"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "apple-newsroom",
    name: "苹果新闻室 Apple Newsroom",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.84,
    credibility: 84,
    requireChinese: false,
    sections: [
      {
        label: "Newsroom",
        url: "https://www.apple.com/newsroom/",
        primaryCategory: "technology",
        categories: ["technology", "ai", "finance"],
        searchTerms: ["Apple Newsroom latest", "Apple product news"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "github-blog",
    name: "GitHub 官方博客",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.8,
    credibility: 80,
    requireChinese: false,
    sections: [
      {
        label: "Blog",
        url: "https://github.blog/",
        primaryCategory: "technology",
        categories: ["technology", "ai"],
        searchTerms: ["GitHub Blog latest", "GitHub developer news"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "21jingji",
    name: "21世纪经济报道",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "business",
    defaultWeight: 0.74,
    credibility: 70,
    requireChinese: true,
    sections: [
      {
        label: "财经",
        url: "https://www.21jingji.com/",
        primaryCategory: "finance",
        categories: ["finance", "china"],
        searchTerms: ["21世纪经济报道 财经", "21世纪经济报道 金融 市场"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "nbs",
    name: "国家统计局",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "official",
    defaultWeight: 0.88,
    credibility: 90,
    requireChinese: true,
    sections: [
      {
        label: "统计数据",
        url: "https://www.stats.gov.cn/",
        primaryCategory: "finance",
        categories: ["finance", "policy", "china"],
        searchTerms: ["国家统计局 数据", "国家统计局 经济 统计"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "pboc",
    name: "中国人民银行",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "official",
    defaultWeight: 0.9,
    credibility: 92,
    requireChinese: true,
    sections: [
      {
        label: "货币政策",
        url: "https://www.pbc.gov.cn/",
        primaryCategory: "finance",
        categories: ["finance", "policy", "china"],
        searchTerms: ["中国人民银行 货币政策", "央行 金融 公告"],
      },
      {
        label: "政策公告",
        url: "https://www.pbc.gov.cn/",
        primaryCategory: "policy",
        categories: ["policy", "finance", "china"],
        searchTerms: ["中国人民银行 政策", "人民银行 公告"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "fed",
    name: "美联储",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.9,
    credibility: 92,
    requireChinese: false,
    sections: [
      {
        label: "Monetary Policy",
        url: "https://www.federalreserve.gov/",
        primaryCategory: "finance",
        categories: ["finance", "policy", "international"],
        searchTerms: ["Federal Reserve monetary policy", "Fed latest news"],
        feedUrl: "https://www.federalreserve.gov/feeds/press_all.xml",
      },
      {
        label: "Press Releases",
        url: "https://www.federalreserve.gov/",
        primaryCategory: "policy",
        categories: ["policy", "finance", "international"],
        searchTerms: ["Federal Reserve press release", "Fed policy statement"],
        feedUrl: "https://www.federalreserve.gov/feeds/press_all.xml",
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "ecb",
    name: "欧洲央行",
    countryOrRegion: "europe",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.88,
    credibility: 90,
    requireChinese: false,
    sections: [
      {
        label: "Monetary Policy",
        url: "https://www.ecb.europa.eu/",
        primaryCategory: "finance",
        categories: ["finance", "policy", "international"],
        searchTerms: ["European Central Bank monetary policy", "ECB latest news"],
      },
      {
        label: "Policy",
        url: "https://www.ecb.europa.eu/",
        primaryCategory: "policy",
        categories: ["policy", "finance", "international"],
        searchTerms: ["ECB policy decision", "European Central Bank press release"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "sse",
    name: "上海证券交易所",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "official",
    defaultWeight: 0.86,
    credibility: 88,
    requireChinese: true,
    sections: [
      {
        label: "市场公告",
        url: "https://www.sse.com.cn/",
        primaryCategory: "finance",
        categories: ["finance", "policy", "china"],
        searchTerms: ["上海证券交易所 公告", "上交所 市场 监管"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "szse",
    name: "深圳证券交易所",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "official",
    defaultWeight: 0.86,
    credibility: 88,
    requireChinese: true,
    sections: [
      {
        label: "市场公告",
        url: "https://www.szse.cn/",
        primaryCategory: "finance",
        categories: ["finance", "policy", "china"],
        searchTerms: ["深圳证券交易所 公告", "深交所 市场 监管"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "hkex",
    name: "香港交易所",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "official",
    defaultWeight: 0.84,
    credibility: 86,
    requireChinese: true,
    sections: [
      {
        label: "市场公告",
        url: "https://www.hkexnews.hk/",
        primaryCategory: "finance",
        categories: ["finance", "policy", "china"],
        searchTerms: ["香港交易所 公告", "港交所 市场 新闻"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "cna",
    name: "亚洲新闻台 CNA",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.8,
    credibility: 80,
    requireChinese: false,
    sections: [
      {
        label: "Asia",
        url: "https://www.channelnewsasia.com/",
        primaryCategory: "international",
        categories: ["international", "finance"],
        searchTerms: ["CNA Asia latest news", "Channel NewsAsia world business"],
        feedUrl: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6511",
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "nhk",
    name: "日本NHK国际广播",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.82,
    credibility: 82,
    requireChinese: false,
    sections: [
      {
        label: "World",
        url: "https://www3.nhk.or.jp/nhkworld/en/news/",
        primaryCategory: "international",
        categories: ["international"],
        searchTerms: ["NHK World Japan latest", "NHK news world"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "dw",
    name: "德国之声 DW",
    countryOrRegion: "europe",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.82,
    credibility: 82,
    requireChinese: false,
    sections: [
      {
        label: "Top Stories",
        url: "https://www.dw.com/en/top-stories/s-9097",
        primaryCategory: "international",
        categories: ["international", "policy"],
        searchTerms: ["DW top stories latest", "Deutsche Welle world news"],
        feedUrl: "https://rss.dw.com/rdf/rss-en-all",
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "france24",
    name: "法国24电视台",
    countryOrRegion: "europe",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.8,
    credibility: 80,
    requireChinese: false,
    sections: [
      {
        label: "News",
        url: "https://www.france24.com/en/",
        primaryCategory: "international",
        categories: ["international", "policy"],
        searchTerms: ["France 24 latest news", "France24 world news"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "africanews",
    name: "非洲新闻台 Africanews",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.74,
    credibility: 72,
    requireChinese: false,
    sections: [
      {
        label: "News",
        url: "https://www.africanews.com/",
        primaryCategory: "international",
        categories: ["international"],
        searchTerms: ["Africanews latest", "Africa news latest"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "agencia-brasil",
    name: "巴西国家通讯社",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.76,
    credibility: 76,
    requireChinese: false,
    sections: [
      {
        label: "News",
        url: "https://agenciabrasil.ebc.com.br/",
        primaryCategory: "international",
        categories: ["international"],
        searchTerms: ["Agencia Brasil latest", "Brazil news latest"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "bjnews",
    name: "新京报",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "commercial",
    defaultWeight: 0.76,
    credibility: 72,
    requireChinese: true,
    sections: [
      {
        label: "要闻",
        url: "https://www.bjnews.com.cn/",
        primaryCategory: "china",
        categories: ["china", "society", "policy"],
        searchTerms: ["新京报 要闻", "新京报 时政 社会"],
      },
      {
        label: "社会",
        url: "https://www.bjnews.com.cn/",
        primaryCategory: "society",
        categories: ["society", "china"],
        searchTerms: ["新京报 社会", "新京报 热点"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "infzm",
    name: "南方周末",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "commercial",
    defaultWeight: 0.74,
    credibility: 72,
    requireChinese: true,
    sections: [
      {
        label: "新闻",
        url: "https://www.infzm.com/",
        primaryCategory: "china",
        categories: ["china", "society", "policy"],
        searchTerms: ["南方周末 新闻", "南方周末 时政 社会"],
      },
      {
        label: "社会",
        url: "https://www.infzm.com/",
        primaryCategory: "society",
        categories: ["society", "china"],
        searchTerms: ["南方周末 社会", "南方周末 调查"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "cyol",
    name: "中国青年报",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "public",
    defaultWeight: 0.76,
    credibility: 74,
    requireChinese: true,
    sections: [
      {
        label: "新闻",
        url: "https://www.cyol.com/",
        primaryCategory: "china",
        categories: ["china", "society", "policy"],
        searchTerms: ["中国青年报 新闻", "中国青年报 社会 青年"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "redstar",
    name: "红星新闻",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "commercial",
    defaultWeight: 0.72,
    credibility: 70,
    requireChinese: true,
    sections: [
      {
        label: "新闻",
        url: "https://www.cdsb.com/",
        primaryCategory: "china",
        categories: ["china", "society"],
        searchTerms: ["红星新闻 新闻", "红星新闻 社会 热点"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "gov-cn",
    name: "中国政府网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "official",
    defaultWeight: 0.92,
    credibility: 94,
    requireChinese: true,
    sections: [
      {
        label: "政策",
        url: "https://www.gov.cn/",
        primaryCategory: "policy",
        categories: ["policy", "china"],
        searchTerms: ["中国政府网 政策", "国务院 政策 发布"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "ndrc",
    name: "国家发展改革委",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "official",
    defaultWeight: 0.88,
    credibility: 90,
    requireChinese: true,
    sections: [
      {
        label: "政策发布",
        url: "https://www.ndrc.gov.cn/",
        primaryCategory: "policy",
        categories: ["policy", "finance", "china"],
        searchTerms: ["国家发展改革委 政策", "发改委 发布 规划"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "mof",
    name: "财政部",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "official",
    defaultWeight: 0.88,
    credibility: 90,
    requireChinese: true,
    sections: [
      {
        label: "政策发布",
        url: "https://www.mof.gov.cn/",
        primaryCategory: "policy",
        categories: ["policy", "finance", "china"],
        searchTerms: ["财政部 政策", "财政部 财政 公告"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "miit",
    name: "工业和信息化部",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "official",
    defaultWeight: 0.86,
    credibility: 88,
    requireChinese: true,
    sections: [
      {
        label: "政策发布",
        url: "https://www.miit.gov.cn/",
        primaryCategory: "policy",
        categories: ["policy", "technology", "china"],
        searchTerms: ["工业和信息化部 政策", "工信部 发布 产业"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "eu-commission",
    name: "欧盟委员会",
    countryOrRegion: "europe",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.86,
    credibility: 88,
    requireChinese: false,
    sections: [
      {
        label: "Press",
        url: "https://commission.europa.eu/",
        primaryCategory: "policy",
        categories: ["policy", "international", "finance"],
        searchTerms: ["European Commission press release", "EU Commission policy latest"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "who",
    name: "世界卫生组织 WHO",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.88,
    credibility: 90,
    requireChinese: false,
    sections: [
      {
        label: "News",
        url: "https://www.who.int/news",
        primaryCategory: "society",
        categories: ["society", "international", "science"],
        searchTerms: ["WHO latest news", "World Health Organization news"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "science-news",
    name: "Science News 科学新闻",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.76,
    credibility: 78,
    requireChinese: false,
    sections: [
      {
        label: "Science",
        url: "https://www.sciencenews.org/",
        primaryCategory: "science",
        categories: ["science", "technology"],
        searchTerms: ["Science News latest", "Science News research"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "nature-news",
    name: "Nature 新闻",
    countryOrRegion: "europe",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.86,
    credibility: 88,
    requireChinese: false,
    sections: [
      {
        label: "News",
        url: "https://www.nature.com/news",
        primaryCategory: "science",
        categories: ["science", "technology"],
        searchTerms: ["Nature news latest", "Nature research news"],
        feedUrl: "https://www.nature.com/nature.rss",
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "nasa",
    name: "NASA 美国航天局",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.88,
    credibility: 90,
    requireChinese: false,
    sections: [
      {
        label: "News",
        url: "https://www.nasa.gov/news/",
        primaryCategory: "science",
        categories: ["science", "technology"],
        searchTerms: ["NASA news latest", "NASA mission news"],
        feedUrl: "https://www.nasa.gov/news-release/feed/",
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "cas",
    name: "中国科学院",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "official",
    defaultWeight: 0.86,
    credibility: 88,
    requireChinese: true,
    sections: [
      {
        label: "科研",
        url: "https://www.cas.cn/",
        primaryCategory: "science",
        categories: ["science", "technology", "china"],
        searchTerms: ["中国科学院 科研", "中科院 科学 进展"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "sciencenet",
    name: "科学网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "commercial",
    defaultWeight: 0.74,
    credibility: 74,
    requireChinese: true,
    sections: [
      {
        label: "科学",
        url: "https://news.sciencenet.cn/",
        primaryCategory: "science",
        categories: ["science", "technology", "china"],
        searchTerms: ["科学网 新闻", "科学网 科研 论文"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "wta",
    name: "WTA 女子网球协会",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.84,
    credibility: 86,
    requireChinese: false,
    sections: [
      {
        label: "News",
        url: "https://www.wtatennis.com/news",
        primaryCategory: "sports",
        categories: ["sports", "international"],
        searchTerms: ["WTA latest news", "WTA tennis news"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "atp",
    name: "ATP 男子网球协会",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.84,
    credibility: 86,
    requireChinese: false,
    sections: [
      {
        label: "News",
        url: "https://www.atptour.com/en/news",
        primaryCategory: "sports",
        categories: ["sports", "international"],
        searchTerms: ["ATP Tour latest news", "ATP tennis news"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "world-athletics",
    name: "世界田联",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.84,
    credibility: 86,
    requireChinese: false,
    sections: [
      {
        label: "News",
        url: "https://worldathletics.org/",
        primaryCategory: "sports",
        categories: ["sports", "international"],
        searchTerms: ["World Athletics latest news", "World Athletics championships"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "olympics",
    name: "国际奥委会 Olympics",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.86,
    credibility: 88,
    requireChinese: false,
    sections: [
      {
        label: "News",
        url: "https://www.olympics.com/en/",
        primaryCategory: "sports",
        categories: ["sports", "international"],
        searchTerms: ["Olympics latest news", "International Olympic Committee news"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "f1",
    name: "F1 世界一级方程式",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.82,
    credibility: 84,
    requireChinese: false,
    sections: [
      {
        label: "Latest",
        url: "https://www.formula1.com/en/latest",
        primaryCategory: "sports",
        categories: ["sports", "international"],
        searchTerms: ["Formula 1 latest news", "F1 racing news"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "deadline",
    name: "Deadline 影视行业新闻",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.76,
    credibility: 76,
    requireChinese: false,
    sections: [
      {
        label: "Film",
        url: "https://deadline.com/",
        primaryCategory: "entertainment",
        categories: ["entertainment", "international"],
        searchTerms: ["Deadline Hollywood latest", "Deadline film TV news"],
        feedUrl: "https://deadline.com/feed/",
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "thr",
    name: "好莱坞报道 The Hollywood Reporter",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.76,
    credibility: 76,
    requireChinese: false,
    sections: [
      {
        label: "Film",
        url: "https://www.hollywoodreporter.com/",
        primaryCategory: "entertainment",
        categories: ["entertainment", "international"],
        searchTerms: ["Hollywood Reporter latest", "THR film TV news"],
      },
    ],
  }),
  defineExpandedSource({
    sourceId: "billboard",
    name: "公告牌 Billboard",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.74,
    credibility: 74,
    requireChinese: false,
    sections: [
      {
        label: "Music",
        url: "https://www.billboard.com/",
        primaryCategory: "entertainment",
        categories: ["entertainment", "international"],
        searchTerms: ["Billboard latest music news", "Billboard charts news"],
      },
    ],
  }),
];
