import type { NewsSource } from "../types";

export const newsSources: NewsSource[] = [
  {
    source_id: "xinhua",
    name: "新华网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "wire",
    defaultWeight: 1,
    credibility: 88,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "要闻", url: "https://www.news.cn/", categories: ["china", "policy", "international"] }],
  },
  {
    source_id: "people",
    name: "人民网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "public",
    defaultWeight: 0.95,
    credibility: 84,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "要闻", url: "https://www.people.com.cn/", categories: ["china", "policy", "society"] }],
  },
  {
    source_id: "cctv",
    name: "央视网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "public",
    defaultWeight: 0.95,
    credibility: 84,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "新闻", url: "https://news.cctv.com/", categories: ["china", "policy", "society"] }],
  },
  {
    source_id: "chinanews",
    name: "中国新闻网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "public",
    defaultWeight: 0.9,
    credibility: 80,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "即时", url: "https://www.chinanews.com.cn/", categories: ["china", "international", "society"] }],
  },
  {
    source_id: "china-daily",
    name: "中国日报网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "public",
    defaultWeight: 0.85,
    credibility: 78,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "新闻", url: "https://cn.chinadaily.com.cn/", categories: ["china", "international"] }],
  },
  {
    source_id: "caixin",
    name: "财新",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "business",
    defaultWeight: 0.9,
    credibility: 82,
    mayHavePaywall: true,
    enabled: true,
    sections: [{ label: "经济", url: "https://www.caixin.com/", categories: ["finance", "china", "policy"] }],
  },
  {
    source_id: "yicai",
    name: "第一财经",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "business",
    defaultWeight: 0.82,
    credibility: 76,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "财经", url: "https://www.yicai.com/", categories: ["finance", "china"] }],
  },
  {
    source_id: "jiemian",
    name: "界面新闻",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "commercial",
    defaultWeight: 0.78,
    credibility: 72,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "快讯", url: "https://www.jiemian.com/", categories: ["finance", "technology", "society"] }],
  },
  {
    source_id: "the-paper",
    name: "澎湃新闻",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "commercial",
    defaultWeight: 0.78,
    credibility: 74,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "新闻", url: "https://www.thepaper.cn/", categories: ["china", "society", "policy"] }],
  },
  {
    source_id: "36kr",
    name: "36氪",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "technology",
    defaultWeight: 0.75,
    credibility: 70,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "科技", url: "https://36kr.com/", categories: ["technology", "ai", "finance"] }],
  },
  {
    source_id: "tmtpost",
    name: "钛媒体",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "technology",
    defaultWeight: 0.72,
    credibility: 68,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "科技", url: "https://www.tmtpost.com/", categories: ["technology", "ai"] }],
  },
  {
    source_id: "jiqizhixin",
    name: "机器之心",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "technology",
    defaultWeight: 0.75,
    credibility: 72,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "人工智能", url: "https://www.jiqizhixin.com/", categories: ["ai", "technology", "science"] }],
  },
  {
    source_id: "qbitai",
    name: "量子位",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "technology",
    defaultWeight: 0.7,
    credibility: 68,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "AI", url: "https://www.qbitai.com/", categories: ["ai", "technology"] }],
  },
  {
    source_id: "bbc-sport",
    name: "BBC体育",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.8,
    credibility: 80,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "Sport", url: "https://www.bbc.com/sport", categories: ["sports", "international"] }],
  },
  {
    source_id: "espn",
    name: "ESPN",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.76,
    credibility: 74,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "Sports", url: "https://www.espn.com/", categories: ["sports", "international"] }],
  },
  {
    source_id: "variety",
    name: "综艺 Variety",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.74,
    credibility: 74,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "Entertainment", url: "https://variety.com/", categories: ["entertainment", "international"] }],
  },
  {
    source_id: "mtime",
    name: "时光网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "commercial",
    defaultWeight: 0.68,
    credibility: 66,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "影视", url: "http://news.mtime.com/", categories: ["entertainment", "china", "society"] }],
  },
  {
    source_id: "reuters",
    name: "Reuters",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "wire",
    defaultWeight: 1,
    credibility: 92,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "World", url: "https://www.reuters.com/world/", categories: ["international", "finance", "policy"] }],
  },
  {
    source_id: "ap",
    name: "Associated Press",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "wire",
    defaultWeight: 1,
    credibility: 91,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "Top News", url: "https://apnews.com/", categories: ["international", "policy", "society"] }],
  },
  {
    source_id: "bbc",
    name: "BBC",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.95,
    credibility: 86,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "World", url: "https://www.bbc.com/news/world", categories: ["international", "policy", "society"] }],
  },
  {
    source_id: "aljazeera",
    name: "Al Jazeera",
    countryOrRegion: "middle-east",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.85,
    credibility: 78,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "News", url: "https://www.aljazeera.com/news/", categories: ["international", "policy", "society"] }],
  },
  {
    source_id: "npr",
    name: "NPR",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.82,
    credibility: 80,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "News", url: "https://www.npr.org/sections/news/", categories: ["international", "policy", "society"] }],
  },
  {
    source_id: "guardian",
    name: "The Guardian",
    countryOrRegion: "europe",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.82,
    credibility: 78,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "World", url: "https://www.theguardian.com/world", categories: ["international", "policy", "society"] }],
  },
  {
    source_id: "bloomberg",
    name: "Bloomberg",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "business",
    defaultWeight: 0.9,
    credibility: 84,
    mayHavePaywall: true,
    enabled: true,
    sections: [{ label: "Markets", url: "https://www.bloomberg.com/markets", categories: ["finance", "international"] }],
  },
  {
    source_id: "ft",
    name: "Financial Times",
    countryOrRegion: "europe",
    language: "en-US",
    mediaType: "business",
    defaultWeight: 0.88,
    credibility: 84,
    mayHavePaywall: true,
    enabled: true,
    sections: [{ label: "World", url: "https://www.ft.com/world", categories: ["finance", "international", "policy"] }],
  },
  {
    source_id: "wsj",
    name: "Wall Street Journal",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "business",
    defaultWeight: 0.86,
    credibility: 82,
    mayHavePaywall: true,
    enabled: true,
    sections: [{ label: "World", url: "https://www.wsj.com/news/world", categories: ["finance", "international"] }],
  },
  {
    source_id: "cnbc",
    name: "CNBC",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "business",
    defaultWeight: 0.78,
    credibility: 74,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "Business", url: "https://www.cnbc.com/world/", categories: ["finance", "technology", "international"] }],
  },
  {
    source_id: "techcrunch",
    name: "TechCrunch",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "technology",
    defaultWeight: 0.78,
    credibility: 74,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "Startups", url: "https://techcrunch.com/", categories: ["technology", "ai", "finance"] }],
  },
  {
    source_id: "the-verge",
    name: "The Verge",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "technology",
    defaultWeight: 0.75,
    credibility: 72,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "Tech", url: "https://www.theverge.com/tech", categories: ["technology", "ai"] }],
  },
  {
    source_id: "wired",
    name: "Wired",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "technology",
    defaultWeight: 0.76,
    credibility: 76,
    mayHavePaywall: true,
    enabled: true,
    sections: [{ label: "Science", url: "https://www.wired.com/category/science/", categories: ["technology", "science", "ai"] }],
  },
  {
    source_id: "ars-technica",
    name: "Ars Technica",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "technology",
    defaultWeight: 0.75,
    credibility: 76,
    mayHavePaywall: false,
    enabled: true,
    sections: [{ label: "Tech", url: "https://arstechnica.com/", categories: ["technology", "science", "ai"] }],
  },
  {
    source_id: "mit-tech-review",
    name: "MIT Technology Review",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "technology",
    defaultWeight: 0.82,
    credibility: 82,
    mayHavePaywall: true,
    enabled: true,
    sections: [{ label: "AI", url: "https://www.technologyreview.com/topic/artificial-intelligence/", categories: ["ai", "technology", "science"] }],
  },
];
