import type { Category, NewsSource, SearchSourceType, SourceSection } from "../types";

const newsOnly: SearchSourceType[] = ["news"];
const webAndNews: SearchSourceType[] = ["web", "news"];

function section(
  label: string,
  url: string,
  primaryCategory: Category,
  categories: Category[],
  searchTerms: string[],
  searchSources: SearchSourceType[] = newsOnly,
  requireChinese = true,
): SourceSection {
  return { label, url, primaryCategory, categories, searchTerms, searchSources, requireChinese };
}

export const newsSources: NewsSource[] = [
  {
    source_id: "xinhua",
    name: "新华网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "wire",
    defaultWeight: 1,
    credibility: 88,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("要闻", "https://www.news.cn/", "china", ["china", "policy", "international"], ["新华网 要闻", "新华社 中国 时政 国际"])],
  },
  {
    source_id: "people",
    name: "人民网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "public",
    defaultWeight: 0.95,
    credibility: 84,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("要闻", "https://www.people.com.cn/", "china", ["china", "policy", "society"], ["人民网 要闻", "人民网 时政 社会"])],
  },
  {
    source_id: "cctv",
    name: "央视网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "public",
    defaultWeight: 0.95,
    credibility: 84,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("新闻", "https://news.cctv.com/", "china", ["china", "policy", "society"], ["央视网 新闻", "央视网 国内 国际"])],
  },
  {
    source_id: "chinanews",
    name: "中国新闻网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "public",
    defaultWeight: 0.9,
    credibility: 80,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("即时", "https://www.chinanews.com.cn/", "china", ["china", "international", "society"], ["中国新闻网 即时新闻", "中新网 中国 国际 社会"])],
  },
  {
    source_id: "china-daily",
    name: "中国日报网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "public",
    defaultWeight: 0.85,
    credibility: 78,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("新闻", "https://cn.chinadaily.com.cn/", "china", ["china", "international"], ["中国日报网 新闻", "China Daily 中文 中国 国际"])],
  },
  {
    source_id: "caixin",
    name: "财新",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "business",
    defaultWeight: 0.9,
    credibility: 82,
    mayHavePaywall: true,
    enabled: true,
    sections: [section("经济", "https://www.caixin.com/", "finance", ["finance", "china", "policy"], ["财新 经济 金融", "财新 财经 政策"])],
  },
  {
    source_id: "yicai",
    name: "第一财经",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "business",
    defaultWeight: 0.82,
    credibility: 76,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("财经", "https://www.yicai.com/", "finance", ["finance", "china"], ["第一财经 财经", "第一财经 市场 公司"])],
  },
  {
    source_id: "jiemian",
    name: "界面新闻",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "commercial",
    defaultWeight: 0.78,
    credibility: 72,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("快讯", "https://www.jiemian.com/", "finance", ["finance", "technology", "society"], ["界面新闻 快讯", "界面新闻 财经 科技"])],
  },
  {
    source_id: "the-paper",
    name: "澎湃新闻",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "commercial",
    defaultWeight: 0.78,
    credibility: 74,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("新闻", "https://www.thepaper.cn/", "china", ["china", "society", "policy"], ["澎湃新闻 时事", "澎湃新闻 社会 政策"])],
  },
  {
    source_id: "36kr",
    name: "36氪",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "technology",
    defaultWeight: 0.75,
    credibility: 70,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("科技", "https://36kr.com/", "technology", ["technology", "ai", "finance"], ["36氪 科技 AI", "36氪 创业 公司"])],
  },
  {
    source_id: "tmtpost",
    name: "钛媒体",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "technology",
    defaultWeight: 0.72,
    credibility: 68,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("科技", "https://www.tmtpost.com/", "technology", ["technology", "ai"], ["钛媒体 科技 AI", "钛媒体 人工智能"])],
  },
  {
    source_id: "jiqizhixin",
    name: "机器之心",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "technology",
    defaultWeight: 0.75,
    credibility: 72,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("人工智能", "https://www.jiqizhixin.com/", "ai", ["ai", "technology", "science"], ["机器之心 人工智能", "机器之心 大模型 论文"])],
  },
  {
    source_id: "qbitai",
    name: "量子位",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "technology",
    defaultWeight: 0.7,
    credibility: 68,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("AI", "https://www.qbitai.com/", "ai", ["ai", "technology"], ["量子位 AI", "量子位 大模型 人工智能"])],
  },
  {
    source_id: "nba",
    name: "NBA官网",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.86,
    credibility: 88,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("NBA News", "https://www.nba.com/news", "sports", ["sports"], ["NBA official news", "NBA latest news trades injuries"], webAndNews, false)],
  },
  {
    source_id: "fifa",
    name: "FIFA官网",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.86,
    credibility: 88,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("FIFA News", "https://www.fifa.com/en/news", "sports", ["sports", "international"], ["FIFA official news", "FIFA World Cup football latest news"], webAndNews, false)],
  },
  {
    source_id: "fiba",
    name: "FIBA官网",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.84,
    credibility: 86,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("FIBA News", "https://www.fiba.basketball/news", "sports", ["sports", "international"], ["FIBA official basketball news", "FIBA basketball latest news"], webAndNews, false)],
  },
  {
    source_id: "bbc-sport",
    name: "BBC体育",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.8,
    credibility: 80,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("Sport", "https://www.bbc.com/sport", "sports", ["sports", "international"], ["BBC Sport latest", "BBC Sport football basketball"], newsOnly, false)],
  },
  {
    source_id: "espn",
    name: "ESPN",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.76,
    credibility: 74,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("NBA", "https://www.espn.com/nba/", "sports", ["sports"], ["ESPN NBA latest news", "ESPN NBA trades injuries"], newsOnly, false)],
  },
  {
    source_id: "yahoo-sports-nba",
    name: "雅虎体育 NBA",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.72,
    credibility: 72,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("NBA", "https://sports.yahoo.com/nba/", "sports", ["sports"], ["Yahoo Sports NBA latest news", "Yahoo Sports NBA trades"], newsOnly, false)],
  },
  {
    source_id: "cbs-sports-nba",
    name: "CBS体育 NBA",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.72,
    credibility: 72,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("NBA", "https://www.cbssports.com/nba/", "sports", ["sports"], ["CBS Sports NBA latest news", "CBS Sports NBA rumors injuries"], newsOnly, false)],
  },
  {
    source_id: "the-athletic-nba",
    name: "The Athletic NBA",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.74,
    credibility: 78,
    mayHavePaywall: true,
    enabled: false,
    sections: [section("NBA", "https://www.nytimes.com/athletic/nba/", "sports", ["sports"], ["The Athletic NBA latest news", "The Athletic NBA trades"], newsOnly, false)],
  },
  {
    source_id: "variety",
    name: "综艺 Variety",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.74,
    credibility: 74,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("Entertainment", "https://variety.com/", "entertainment", ["entertainment", "international"], ["Variety entertainment news", "Variety film TV industry"], newsOnly, false)],
  },
  {
    source_id: "mtime",
    name: "时光网",
    countryOrRegion: "china",
    language: "zh-CN",
    mediaType: "commercial",
    defaultWeight: 0.68,
    credibility: 66,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("影视", "http://news.mtime.com/", "entertainment", ["entertainment", "china", "society"], ["时光网 影视 新闻", "时光网 电影 电视"])],
  },
  {
    source_id: "reuters",
    name: "Reuters",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "wire",
    defaultWeight: 1,
    credibility: 92,
    mayHavePaywall: false,
    enabled: false,
    sections: [section("World", "https://www.reuters.com/world/", "international", ["international", "finance", "policy"], ["Reuters world latest news", "Reuters global politics markets"], newsOnly, false)],
  },
  {
    source_id: "ap",
    name: "Associated Press",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "wire",
    defaultWeight: 1,
    credibility: 91,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("Top News", "https://apnews.com/", "international", ["international", "policy", "society"], ["Associated Press top news", "AP world news"], newsOnly, false)],
  },
  {
    source_id: "bbc",
    name: "BBC",
    countryOrRegion: "global",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.95,
    credibility: 86,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("World", "https://www.bbc.com/news/world", "international", ["international", "policy", "society"], ["BBC world news latest", "BBC international news"], newsOnly, false)],
  },
  {
    source_id: "aljazeera",
    name: "Al Jazeera",
    countryOrRegion: "middle-east",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.85,
    credibility: 78,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("News", "https://www.aljazeera.com/news/", "international", ["international", "policy", "society"], ["Al Jazeera latest news", "Al Jazeera world news"], newsOnly, false)],
  },
  {
    source_id: "npr",
    name: "NPR",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "public",
    defaultWeight: 0.82,
    credibility: 80,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("News", "https://www.npr.org/sections/news/", "international", ["international", "policy", "society"], ["NPR latest news", "NPR world news"], newsOnly, false)],
  },
  {
    source_id: "guardian",
    name: "The Guardian",
    countryOrRegion: "europe",
    language: "en-US",
    mediaType: "commercial",
    defaultWeight: 0.82,
    credibility: 78,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("World", "https://www.theguardian.com/world", "international", ["international", "policy", "society"], ["The Guardian world news", "Guardian latest international"], newsOnly, false)],
  },
  {
    source_id: "bloomberg",
    name: "Bloomberg",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "business",
    defaultWeight: 0.9,
    credibility: 84,
    mayHavePaywall: true,
    enabled: false,
    sections: [section("Markets", "https://www.bloomberg.com/markets", "finance", ["finance", "international"], ["Bloomberg markets latest news", "Bloomberg business finance"], newsOnly, false)],
  },
  {
    source_id: "ft",
    name: "Financial Times",
    countryOrRegion: "europe",
    language: "en-US",
    mediaType: "business",
    defaultWeight: 0.88,
    credibility: 84,
    mayHavePaywall: true,
    enabled: false,
    sections: [section("World", "https://www.ft.com/world", "finance", ["finance", "international", "policy"], ["Financial Times world business", "FT global economy markets"], newsOnly, false)],
  },
  {
    source_id: "wsj",
    name: "Wall Street Journal",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "business",
    defaultWeight: 0.86,
    credibility: 82,
    mayHavePaywall: true,
    enabled: false,
    sections: [section("World", "https://www.wsj.com/news/world", "finance", ["finance", "international"], ["Wall Street Journal world business", "WSJ markets economy"], newsOnly, false)],
  },
  {
    source_id: "cnbc",
    name: "CNBC",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "business",
    defaultWeight: 0.78,
    credibility: 74,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("Business", "https://www.cnbc.com/world/", "finance", ["finance", "technology", "international"], ["CNBC business markets latest", "CNBC technology economy"], newsOnly, false)],
  },
  {
    source_id: "techcrunch",
    name: "TechCrunch",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "technology",
    defaultWeight: 0.78,
    credibility: 74,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("Startups", "https://techcrunch.com/", "technology", ["technology", "ai", "finance"], ["TechCrunch AI startups latest", "TechCrunch technology news"], newsOnly, false)],
  },
  {
    source_id: "the-verge",
    name: "The Verge",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "technology",
    defaultWeight: 0.75,
    credibility: 72,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("Tech", "https://www.theverge.com/tech", "technology", ["technology", "ai"], ["The Verge tech AI latest", "The Verge technology news"], newsOnly, false)],
  },
  {
    source_id: "wired",
    name: "Wired",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "technology",
    defaultWeight: 0.76,
    credibility: 76,
    mayHavePaywall: true,
    enabled: true,
    sections: [section("Science", "https://www.wired.com/category/science/", "science", ["technology", "science", "ai"], ["Wired science AI latest", "Wired technology science"], newsOnly, false)],
  },
  {
    source_id: "ars-technica",
    name: "Ars Technica",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "technology",
    defaultWeight: 0.75,
    credibility: 76,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("Tech", "https://arstechnica.com/", "technology", ["technology", "science", "ai"], ["Ars Technica tech AI", "Ars Technica science technology"], newsOnly, false)],
  },
  {
    source_id: "mit-tech-review",
    name: "MIT Technology Review",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "technology",
    defaultWeight: 0.82,
    credibility: 82,
    mayHavePaywall: true,
    enabled: true,
    sections: [section("AI", "https://www.technologyreview.com/topic/artificial-intelligence/", "ai", ["ai", "technology", "science"], ["MIT Technology Review AI latest", "MIT Tech Review artificial intelligence"], newsOnly, false)],
  },
  {
    source_id: "openai",
    name: "OpenAI",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.9,
    credibility: 90,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("News", "https://openai.com/news/", "ai", ["ai", "technology"], ["OpenAI news latest", "OpenAI blog product research"], webAndNews, false)],
  },
  {
    source_id: "anthropic",
    name: "Anthropic",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.9,
    credibility: 90,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("News", "https://www.anthropic.com/news", "ai", ["ai", "technology"], ["Anthropic news Claude latest", "Anthropic blog research product"], webAndNews, false)],
  },
  {
    source_id: "google-deepmind",
    name: "Google DeepMind",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.88,
    credibility: 88,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("Blog", "https://deepmind.google/discover/blog/", "ai", ["ai", "technology", "science"], ["Google DeepMind blog latest", "DeepMind AI research news"], webAndNews, false)],
  },
  {
    source_id: "google-ai",
    name: "Google AI",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.86,
    credibility: 86,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("Blog", "https://blog.google/technology/ai/", "ai", ["ai", "technology"], ["Google AI blog latest", "Google artificial intelligence news"], webAndNews, false)],
  },
  {
    source_id: "meta-ai",
    name: "Meta AI",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.84,
    credibility: 84,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("Blog", "https://ai.meta.com/blog/", "ai", ["ai", "technology"], ["Meta AI blog latest", "Meta artificial intelligence research"], webAndNews, false)],
  },
  {
    source_id: "microsoft-ai",
    name: "Microsoft AI",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.84,
    credibility: 84,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("Blog", "https://blogs.microsoft.com/ai/", "ai", ["ai", "technology"], ["Microsoft AI blog latest", "Microsoft artificial intelligence news"], webAndNews, false)],
  },
  {
    source_id: "nvidia-ai",
    name: "NVIDIA AI",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.84,
    credibility: 84,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("Blog", "https://blogs.nvidia.com/blog/category/deep-learning/", "ai", ["ai", "technology"], ["NVIDIA AI blog latest", "NVIDIA deep learning news"], webAndNews, false)],
  },
  {
    source_id: "hugging-face",
    name: "Hugging Face",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "official",
    defaultWeight: 0.82,
    credibility: 82,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("Blog", "https://huggingface.co/blog", "ai", ["ai", "technology"], ["Hugging Face blog latest", "Hugging Face AI models news"], webAndNews, false)],
  },
  {
    source_id: "x-shams",
    name: "Shams Charania",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "social",
    defaultWeight: 0.58,
    credibility: 58,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("X", "https://x.com/ShamsCharania", "sports", ["sports"], ["site:x.com/ShamsCharania NBA", "Shams Charania NBA latest"], webAndNews, false)],
  },
  {
    source_id: "x-openai",
    name: "OpenAI X",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "social",
    defaultWeight: 0.6,
    credibility: 62,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("X", "https://x.com/OpenAI", "ai", ["ai", "technology"], ["site:x.com/OpenAI OpenAI latest", "OpenAI X latest"], webAndNews, false)],
  },
  {
    source_id: "x-anthropic",
    name: "Anthropic X",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "social",
    defaultWeight: 0.6,
    credibility: 62,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("X", "https://x.com/AnthropicAI", "ai", ["ai", "technology"], ["site:x.com/AnthropicAI Claude latest", "Anthropic X latest"], webAndNews, false)],
  },
  {
    source_id: "x-sam-altman",
    name: "Sam Altman X",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "social",
    defaultWeight: 0.55,
    credibility: 55,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("X", "https://x.com/sama", "ai", ["ai", "technology"], ["site:x.com/sama OpenAI AI", "Sam Altman AI latest"], webAndNews, false)],
  },
  {
    source_id: "x-greg-brockman",
    name: "Greg Brockman X",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "social",
    defaultWeight: 0.52,
    credibility: 54,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("X", "https://x.com/gdb", "ai", ["ai", "technology"], ["site:x.com/gdb OpenAI AI", "Greg Brockman AI latest"], webAndNews, false)],
  },
  {
    source_id: "x-deepmind",
    name: "Google DeepMind X",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "social",
    defaultWeight: 0.58,
    credibility: 60,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("X", "https://x.com/GoogleDeepMind", "ai", ["ai", "technology", "science"], ["site:x.com/GoogleDeepMind AI", "Google DeepMind X latest"], webAndNews, false)],
  },
  {
    source_id: "x-karpathy",
    name: "Andrej Karpathy X",
    countryOrRegion: "us",
    language: "en-US",
    mediaType: "social",
    defaultWeight: 0.5,
    credibility: 52,
    mayHavePaywall: false,
    enabled: true,
    sections: [section("X", "https://x.com/karpathy", "ai", ["ai", "technology"], ["site:x.com/karpathy AI", "Andrej Karpathy AI latest"], webAndNews, false)],
  },
];
