import type { Category, Locale, Region } from "../types";

/** Supplied account kind. Kept separate from user confirmation and identity evidence. */
export type XAccountKind = "机构官方" | "个人" | "记者";

/**
 * Registry entry for one approved X handle. `userConfirmed` reflects the user's
 * explicit decision, while `identityStatus`, `evidenceUrl`, `evidenceNote` and
 * `affiliationStatus` carry the independent identity notes. Pending proposals
 * (`userConfirmed: false`) stay present but are emitted as disabled sources.
 */
export interface XAccountRegistryEntry {
  handle: string;
  name: string;
  categories: Category[];
  kind: XAccountKind;
  topic: string;
  decision: string;
  identityStatus: string;
  evidenceUrl: string;
  evidenceNote: string;
  affiliationStatus: string | null;
  userConfirmed: boolean;
  /** Stable id for the seven pre-expansion X sources whose ids must be preserved. */
  existingSourceId?: string;
  countryOrRegion: Region;
  language: Locale;
  defaultWeight: number;
  credibility: number;
}

interface XAccountInput {
  handle: string;
  name: string;
  categories: Category[];
  kind: XAccountKind;
  topic: string;
  decision: string;
  identityStatus: string;
  evidenceUrl: string;
  evidenceNote: string;
  affiliationStatus: string | null;
  userConfirmed: boolean;
  existingSourceId?: string;
  countryOrRegion?: Region;
  language?: Locale;
  defaultWeight?: number;
  credibility?: number;
}

function xAccount(input: XAccountInput): XAccountRegistryEntry {
  return {
    handle: input.handle,
    name: input.name,
    categories: input.categories,
    kind: input.kind,
    topic: input.topic,
    decision: input.decision,
    identityStatus: input.identityStatus,
    evidenceUrl: input.evidenceUrl,
    evidenceNote: input.evidenceNote,
    affiliationStatus: input.affiliationStatus,
    userConfirmed: input.userConfirmed,
    ...(input.existingSourceId ? { existingSourceId: input.existingSourceId } : {}),
    countryOrRegion: input.countryOrRegion ?? "us",
    language: input.language ?? "en-US",
    defaultWeight: input.defaultWeight ?? 0.52,
    credibility: input.credibility ?? 54,
  };
}

/** Stable generated source id for an approved X handle. */
export function xSourceId(handle: string): string {
  return `x-${handle.toLowerCase()}`;
}

export const xAccountRegistry: XAccountRegistryEntry[] = [
  xAccount({
    handle: "OpenAI",
    name: "OpenAI",
    categories: ["ai"],
    kind: "机构官方",
    topic: "模型与产品",
    decision: "保留",
    identityStatus: "已核对官方链接",
    evidenceUrl: "https://help.openai.com/en/articles/11725090",
    evidenceNote: "官方帮助中心社交账号清单列出 @OpenAI",
    affiliationStatus: null,
    userConfirmed: true,
    existingSourceId: "x-openai",
    defaultWeight: 0.6,
    credibility: 62,
  }),
  xAccount({
    handle: "AnthropicAI",
    name: "Anthropic",
    categories: ["ai"],
    kind: "机构官方",
    topic: "Claude与AI安全",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.anthropic.com/",
    evidenceNote: "2026-09-13 公开页面含 https://x.com/AnthropicAI",
    affiliationStatus: null,
    userConfirmed: true,
    existingSourceId: "x-anthropic",
    defaultWeight: 0.6,
    credibility: 62,
  }),
  xAccount({
    handle: "GoogleDeepMind",
    name: "Google DeepMind",
    categories: ["ai"],
    kind: "机构官方",
    topic: "前沿研究",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://deepmind.google/",
    evidenceNote: "2026-09-13 公开页面含 https://x.com/googledeepmind",
    affiliationStatus: null,
    userConfirmed: true,
    existingSourceId: "x-deepmind",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "GoogleAI",
    name: "Google AI",
    categories: ["ai"],
    kind: "机构官方",
    topic: "Gemini与研究",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://ai.google/",
    evidenceNote: "2026-09-13 公开页面含 https://x.com/Googleai",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "AIatMeta",
    name: "Meta AI",
    categories: ["ai"],
    kind: "机构官方",
    topic: "开源模型与研究",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://ai.meta.com/blog/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/aiatmeta",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "MicrosoftAI",
    name: "Microsoft AI",
    categories: ["ai"],
    kind: "机构官方",
    topic: "Copilot与AI产品",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://microsoft.ai/",
    evidenceNote: "2026-09-13 公开页面含 https://www.x.com/MicrosoftAI",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "NVIDIAAI",
    name: "NVIDIA AI",
    categories: ["ai"],
    kind: "机构官方",
    topic: "算力与模型",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://www.nvidia.com/en-us/ai/",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：官方AI页面确认业务，句柄需核验",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "huggingface",
    name: "Hugging Face",
    categories: ["ai"],
    kind: "机构官方",
    topic: "开源模型",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://huggingface.co/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/huggingface",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "deepseek_ai",
    name: "DeepSeek",
    categories: ["ai"],
    kind: "机构官方",
    topic: "开源模型",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.deepseek.com/",
    evidenceNote: "2026-09-13 公开页面含 https://x.com/deepseek_ai",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "china",
    language: "zh-CN",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "Alibaba_Qwen",
    name: "Qwen",
    categories: ["ai"],
    kind: "机构官方",
    topic: "通义千问",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://github.com/QwenLM",
    evidenceNote: "2026-09-13 公开页面含 https://x.com/Alibaba_Qwen",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "china",
    language: "zh-CN",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "Zai_org",
    name: "Z.ai",
    categories: ["ai"],
    kind: "机构官方",
    topic: "GLM模型",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://docs.z.ai/",
    evidenceNote: "2026-09-13 公开页面含 https://x.com/Zai_org",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "china",
    language: "zh-CN",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "sama",
    name: "Sam Altman",
    categories: ["ai"],
    kind: "个人",
    topic: "OpenAI与AI产业",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://blog.samaltman.com/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/sama",
    affiliationStatus: null,
    userConfirmed: true,
    existingSourceId: "x-sam-altman",
    defaultWeight: 0.55,
    credibility: 55,
  }),
  xAccount({
    handle: "gdb",
    name: "Greg Brockman",
    categories: ["ai"],
    kind: "个人",
    topic: "OpenAI工程与产品",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://gregbrockman.com/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/gdb",
    affiliationStatus: null,
    userConfirmed: true,
    existingSourceId: "x-greg-brockman",
    defaultWeight: 0.52,
    credibility: 54,
  }),
  xAccount({
    handle: "karpathy",
    name: "Andrej Karpathy",
    categories: ["ai"],
    kind: "个人",
    topic: "深度学习教育与研究",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://karpathy.ai/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/karpathy",
    affiliationStatus: null,
    userConfirmed: true,
    existingSourceId: "x-karpathy",
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "demishassabis",
    name: "Demis Hassabis",
    categories: ["ai"],
    kind: "个人",
    topic: "Google DeepMind研究",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://deepmind.google/about/",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：官网确认其CEO身份，但未确认X句柄",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "europe",
    defaultWeight: 0.55,
    credibility: 55,
  }),
  xAccount({
    handle: "polynoamial",
    name: "Noam Brown",
    categories: ["ai"],
    kind: "个人",
    topic: "推理与博弈AI",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://noambrown.github.io/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/polynoamial",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.52,
    credibility: 54,
  }),
  xAccount({
    handle: "_jasonwei",
    name: "Jason Wei",
    categories: ["ai"],
    kind: "个人",
    topic: "大模型推理",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.jasonwei.net/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/_jasonwei",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.52,
    credibility: 54,
  }),
  xAccount({
    handle: "bcherny",
    name: "Boris Cherny",
    categories: ["ai"],
    kind: "个人",
    topic: "AI编程工具",
    decision: "保留",
    identityStatus: "已核对采访资料",
    evidenceUrl: "https://newsletter.pragmaticengineer.com/p/building-claude-code-with-boris-cherny",
    evidenceNote: "本人受访节目的嘉宾资料直接列出 X @bcherny",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.52,
    credibility: 54,
  }),
  xAccount({
    handle: "ylecun",
    name: "Yann LeCun",
    categories: ["ai"],
    kind: "个人",
    topic: "机器学习研究",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://cs.nyu.edu/~yann/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/ylecun",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.55,
    credibility: 55,
  }),
  xAccount({
    handle: "fchollet",
    name: "François Chollet",
    categories: ["ai"],
    kind: "个人",
    topic: "智能与推理研究",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://fchollet.com/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/fchollet",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.55,
    credibility: 55,
  }),
  xAccount({
    handle: "thsottiaux",
    name: "Tibo（Thibault Sottiaux）",
    categories: ["ai", "technology"],
    kind: "个人",
    topic: "OpenAI、Codex 与 ChatGPT 产品和工程动态",
    decision: "保留",
    identityStatus: "用户纠正并确认；公开资料佐证",
    evidenceUrl: "https://github.com/thsottiaux",
    evidenceNote: "用户明确纠正为 @thsottiaux；GitHub 搜索结果列 Thibault Sottiaux、OpenAI、Building ChatGPT & Codex；当前本机 GET 返回 404，未据此声称直连成功",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.52,
    credibility: 54,
  }),
  xAccount({
    handle: "ShamsCharania",
    name: "Shams Charania",
    categories: ["sports"],
    kind: "记者",
    topic: "NBA",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://espnpressroom.com/us/bios/shams-charania/",
    evidenceNote: "2026-09-13 公开页面含 https://x.com/ShamsCharania",
    affiliationStatus: null,
    userConfirmed: true,
    existingSourceId: "x-shams",
    defaultWeight: 0.58,
    credibility: 58,
  }),
  xAccount({
    handle: "FabrizioRomano",
    name: "Fabrizio Romano",
    categories: ["sports"],
    kind: "记者",
    topic: "足球转会",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.youtube.com/@FabrizioRomanoYT/about",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/FabrizioRomano",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "europe",
    defaultWeight: 0.58,
    credibility: 58,
  }),
  xAccount({
    handle: "NBA",
    name: "NBA",
    categories: ["sports"],
    kind: "机构官方",
    topic: "篮球",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.nba.com/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/NBA",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "FIFAcom",
    name: "FIFA",
    categories: ["sports"],
    kind: "机构官方",
    topic: "足球",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://inside.fifa.com/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/FIFAcom",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "FIBA",
    name: "FIBA",
    categories: ["sports"],
    kind: "机构官方",
    topic: "篮球",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.fiba.basketball/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/FIBA",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "WTA",
    name: "WTA",
    categories: ["sports"],
    kind: "机构官方",
    topic: "网球",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.wtatennis.com/news",
    evidenceNote: "2026-09-13 公开页面含 https://www.twitter.com/WTA",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "atptour",
    name: "ATP Tour",
    categories: ["sports"],
    kind: "机构官方",
    topic: "网球",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://www.atptour.com/",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：官网入口可核对社交链接",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "WorldAthletics",
    name: "World Athletics",
    categories: ["sports"],
    kind: "机构官方",
    topic: "田径",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://worldathletics.org/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/WorldAthletics",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "Olympics",
    name: "Olympics",
    categories: ["sports"],
    kind: "机构官方",
    topic: "奥运会",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://olympics.com/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/Olympics",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "F1",
    name: "Formula 1",
    categories: ["sports"],
    kind: "机构官方",
    topic: "赛车",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.formula1.com/en/latest",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/f1",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "AP",
    name: "Associated Press",
    categories: ["international"],
    kind: "机构官方",
    topic: "国际新闻",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://www.ap.org/",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：官网需核对具体新闻账号与企业账号，避免误收AP_CorpComm",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "BBCWorld",
    name: "BBC World",
    categories: ["international"],
    kind: "机构官方",
    topic: "国际新闻",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://www.bbc.com/news",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：官网入口可核对社交链接",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "AFP",
    name: "法新社 AFP 新闻",
    categories: ["international"],
    kind: "机构官方",
    topic: "国际新闻",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://www.afp.com/en",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：拟选新闻账号 @AFP；不以企业宣传号 afpcom 替代，句柄仍需进一步核验",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "europe",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "ChannelNewsAsia",
    name: "CNA",
    categories: ["international"],
    kind: "机构官方",
    topic: "亚洲新闻",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.channelnewsasia.com/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/ChannelNewsAsia",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "dwnews",
    name: "DW News",
    categories: ["international"],
    kind: "机构官方",
    topic: "国际新闻",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.dw.com/en/top-stories/s-9097",
    evidenceNote: "2026-09-13 公开页面含 https://x.com/dwnews",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "europe",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "XHNews",
    name: "新华网",
    categories: ["china", "international"],
    kind: "机构官方",
    topic: "中国新闻",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://www.news.cn/",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：官网入口可核对社交链接",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "china",
    language: "zh-CN",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "CCTVNews",
    name: "央视新闻",
    categories: ["china", "international"],
    kind: "机构官方",
    topic: "中国新闻",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://news.cctv.com/",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：官网入口可核对社交链接",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "china",
    language: "zh-CN",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "ChinaDaily",
    name: "China Daily",
    categories: ["china", "international"],
    kind: "机构官方",
    topic: "中国新闻",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://www.chinadaily.com.cn/",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：官网入口可核对社交链接",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "china",
    language: "zh-CN",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "federalreserve",
    name: "Federal Reserve",
    categories: ["finance", "policy"],
    kind: "机构官方",
    topic: "货币政策",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.federalreserve.gov/",
    evidenceNote: "2026-09-13 公开页面含 https://x.com/federalreserve",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.6,
    credibility: 62,
  }),
  xAccount({
    handle: "ecb",
    name: "European Central Bank",
    categories: ["finance", "policy"],
    kind: "机构官方",
    topic: "货币政策",
    decision: "保留",
    identityStatus: "已核对官方链接",
    evidenceUrl: "https://www.ecb.europa.eu/home/html/follow_us.en.html",
    evidenceNote: "官方社交链接页列出 x.com/ecb；当前本机 GET 受证书链影响",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "europe",
    defaultWeight: 0.6,
    credibility: 62,
  }),
  xAccount({
    handle: "IMFNews",
    name: "IMF",
    categories: ["finance"],
    kind: "机构官方",
    topic: "宏观经济",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://www.imf.org/",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：官网入口可核对社交链接",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "WorldBank",
    name: "World Bank",
    categories: ["finance"],
    kind: "机构官方",
    topic: "发展经济",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.worldbank.org/en/home",
    evidenceNote: "2026-09-13 公开页面含 https://x.com/worldbank",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "EU_Commission",
    name: "European Commission",
    categories: ["policy"],
    kind: "机构官方",
    topic: "欧盟政策",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://commission.europa.eu/",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：官网入口可核对社交链接",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "europe",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "WHO",
    name: "WHO",
    categories: ["society"],
    kind: "机构官方",
    topic: "公共卫生",
    decision: "保留",
    identityStatus: "已核对官方链接",
    evidenceUrl: "https://www.who.int/",
    evidenceNote: "官方页面关注按钮 screen_name=who",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    defaultWeight: 0.6,
    credibility: 62,
  }),
  xAccount({
    handle: "UN_News_Centre",
    name: "UN News",
    categories: ["international", "society"],
    kind: "机构官方",
    topic: "联合国新闻",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://news.un.org/en/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/UN_News_Centre",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "NASA",
    name: "NASA",
    categories: ["science"],
    kind: "机构官方",
    topic: "航天科学",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.nasa.gov/social-media/",
    evidenceNote: "2026-09-13 公开页面含 https://x.com/NASA",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.6,
    credibility: 62,
  }),
  xAccount({
    handle: "esa",
    name: "ESA",
    categories: ["science"],
    kind: "机构官方",
    topic: "航天科学",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.esa.int/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/esa",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "europe",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "nature",
    name: "Nature",
    categories: ["science"],
    kind: "机构官方",
    topic: "科学研究",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.nature.com/nature/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/nature",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "europe",
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "sciencemagazine",
    name: "Science Magazine",
    categories: ["science"],
    kind: "机构官方",
    topic: "科学研究",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://www.science.org/",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：官网入口可核对社交链接",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "Variety",
    name: "Variety",
    categories: ["entertainment"],
    kind: "机构官方",
    topic: "影视行业",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://variety.com/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/variety",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "DEADLINE",
    name: "Deadline",
    categories: ["entertainment"],
    kind: "机构官方",
    topic: "影视行业",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://deadline.com/",
    evidenceNote: "2026-09-13 公开页面含 https://x.com/deadline",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "THR",
    name: "The Hollywood Reporter",
    categories: ["entertainment"],
    kind: "机构官方",
    topic: "影视行业",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.hollywoodreporter.com/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/thr",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "billboard",
    name: "Billboard",
    categories: ["entertainment"],
    kind: "机构官方",
    topic: "音乐行业",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.billboard.com/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/billboard",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "ScienceNews",
    name: "Science News",
    categories: ["science"],
    kind: "机构官方",
    topic: "科学报道",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.sciencenews.org/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/sciencenews",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "AndrewYNg",
    name: "Andrew Ng（吴恩达）",
    categories: ["ai"],
    kind: "个人",
    topic: "AI 技术、教育与产业",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://www.andrewng.org/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/AndrewYNg",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.55,
    credibility: 55,
  }),
  xAccount({
    handle: "drfeifei",
    name: "Fei-Fei Li（李飞飞）",
    categories: ["ai"],
    kind: "个人",
    topic: "空间智能与视觉研究",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://profiles.stanford.edu/fei-fei-li",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：候选账号；需要本人或机构公开资料确认",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.55,
    credibility: 55,
  }),
  xAccount({
    handle: "JustinLin610",
    name: "Junyang Lin（林俊旸）",
    categories: ["ai"],
    kind: "个人",
    topic: "大模型研究与开源发布",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://github.com/JunyangLin",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：候选账号；需要本人或机构公开资料确认",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "china",
    language: "zh-CN",
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "ClementDelangue",
    name: "Clément Delangue",
    categories: ["ai"],
    kind: "个人",
    topic: "开源 AI 与生态",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://huggingface.co/clem",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/clementdelangue",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.52,
    credibility: 54,
  }),
  xAccount({
    handle: "DarioAmodei",
    name: "Dario Amodei",
    categories: ["ai"],
    kind: "个人",
    topic: "AI 研究、产业与安全",
    decision: "保留",
    identityStatus: "用户确认；未独立核验",
    evidenceUrl: "https://www.darioamodei.com/",
    evidenceNote: "2026-09-13 用户确认其余候选账号正确。此前独立核验说明：候选账号；需要本人或机构公开资料确认",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.55,
    credibility: 55,
  }),
  xAccount({
    handle: "addyosmani",
    name: "Addy Osmani",
    categories: ["technology", "ai"],
    kind: "个人",
    topic: "开发工具与 AI 工程实践",
    decision: "保留",
    identityStatus: "已核对官方 / 本人链接",
    evidenceUrl: "https://addyosmani.com/",
    evidenceNote: "2026-09-13 公开页面含 https://twitter.com/addyosmani",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "ZixuanLi_",
    name: "Zixuan Li",
    categories: ["ai"],
    kind: "个人",
    topic: "AI 研究、模型与产品动态",
    decision: "保留",
    identityStatus: "用户指定；待 API 接入验证",
    evidenceUrl: "https://x.com/ZixuanLi_",
    evidenceNote: "2026-09-13 用户明确提供账号；ZixuanLi_ 的下划线已从消息中的 Markdown 转义还原",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "china",
    language: "zh-CN",
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "arena",
    name: "Arena",
    categories: ["ai"],
    kind: "机构官方",
    topic: "模型评测、榜单与平台公告",
    decision: "保留",
    identityStatus: "已核对官网 / 本人链接",
    evidenceUrl: "https://arena.ai/",
    evidenceNote: "2026-09-13 页面含 https://x.com/arena。",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.58,
    credibility: 60,
  }),
  xAccount({
    handle: "Khazix0918",
    name: "数字生命卡兹克",
    categories: ["ai", "technology"],
    kind: "个人",
    topic: "中文 AI 产品、应用与行业动态",
    decision: "保留",
    identityStatus: "用户指定；待 API 接入验证",
    evidenceUrl: "https://x.com/Khazix0918",
    evidenceNote: "2026-09-13 用户明确提供账号；ZixuanLi_ 的下划线已从消息中的 Markdown 转义还原",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "china",
    language: "zh-CN",
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "derrickcchoi",
    name: "Derrick Choi",
    categories: ["ai", "technology"],
    kind: "个人",
    topic: "Codex、AI 产品与企业应用",
    decision: "保留",
    identityStatus: "已核对官网 / 本人链接",
    evidenceUrl: "https://derrickchoi.com/",
    evidenceNote: "2026-09-13 页面含 https://x.com/derrickcchoi。",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "elonmusk",
    name: "Elon Musk",
    categories: ["ai", "technology"],
    kind: "个人",
    topic: "AI、Grok 与科技；按新闻主题筛选",
    decision: "保留",
    identityStatus: "用户指定；待 API 接入验证",
    evidenceUrl: "https://x.com/elonmusk",
    evidenceNote: "2026-09-13 用户明确提供账号；ZixuanLi_ 的下划线已从消息中的 Markdown 转义还原",
    affiliationStatus: null,
    userConfirmed: true,
    defaultWeight: 0.55,
    credibility: 55,
  }),
  xAccount({
    handle: "tianyi",
    name: "tianyi",
    categories: ["ai", "technology"],
    kind: "个人",
    topic: "用户指定；按 AI 与科技新闻相关性筛选",
    decision: "保留",
    identityStatus: "用户指定；待 API 接入验证",
    evidenceUrl: "https://x.com/tianyi",
    evidenceNote: "2026-09-13 用户明确提供账号；ZixuanLi_ 的下划线已从消息中的 Markdown 转义还原",
    affiliationStatus: null,
    userConfirmed: true,
    countryOrRegion: "global",
    language: "zh-CN",
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "SpaceXAI",
    name: "xAI（官网当前社交入口）",
    categories: ["ai"],
    kind: "机构官方",
    topic: "公司与研究公告",
    decision: "待确认",
    identityStatus: "已核对官网 / 本人链接",
    evidenceUrl: "https://x.ai/",
    evidenceNote: "2026-09-13 页面含 https://x.com/spacexai。官网当前指向的机构账号",
    affiliationStatus: "官网当前指向的机构账号",
    userConfirmed: false,
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "grok",
    name: "Grok",
    categories: ["ai"],
    kind: "机构官方",
    topic: "仅收原创产品公告；排除自动问答回复与转发",
    decision: "待确认",
    identityStatus: "已核对官网 / 本人链接",
    evidenceUrl: "https://x.ai/",
    evidenceNote: "2026-09-13 页面含 https://x.com/grok。Grok 产品官方账号",
    affiliationStatus: "Grok 产品官方账号",
    userConfirmed: false,
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "ibab",
    name: "Igor Babuschkin",
    categories: ["ai"],
    kind: "个人",
    topic: "AI 工程、研究与创业",
    decision: "待确认",
    identityStatus: "已核对本人帖文存档",
    evidenceUrl: "https://threadreaderapp.com/thread/1955741698690322585.html",
    evidenceNote: "本人 2025-08-13 离职帖存档，附原帖链接；不再使用初步候选中的错误姓名",
    affiliationStatus: "前 xAI 联合创始人；已离职",
    userConfirmed: false,
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "TobyPhln",
    name: "Toby Pohlen",
    categories: ["ai"],
    kind: "个人",
    topic: "AI 工程、智能体与研究",
    decision: "待确认",
    identityStatus: "已核对公开 X 简介",
    evidenceUrl: "https://x.com/TobyPhln/with_replies",
    evidenceNote: "公开 X 简介写明 Previously founding team @xAI",
    affiliationStatus: "前 xAI 创始团队成员",
    userConfirmed: false,
    countryOrRegion: "europe",
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "Yuhu_ai_",
    name: "Yuhuai (Tony) Wu",
    categories: ["ai"],
    kind: "个人",
    topic: "推理、数学与模型研究",
    decision: "待确认",
    identityStatus: "已核对官网 / 本人链接",
    evidenceUrl: "https://yuhuaiwu.github.io/",
    evidenceNote: "2026-09-13 页面含 https://twitter.com/Yuhu_ai_。历史创始成员；有本人离职声明",
    affiliationStatus: "历史创始成员；有本人离职声明",
    userConfirmed: false,
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "jimmybajimmyba",
    name: "Jimmy Ba",
    categories: ["ai"],
    kind: "个人",
    topic: "模型训练、研究与 AI 行业",
    decision: "待确认",
    identityStatus: "已核对公开 X 简介",
    evidenceUrl: "https://x.com/jimmybajimmyba/with_replies",
    evidenceNote: "公开 X 搜索资料明确绑定姓名与完整 handle；初步候选 jimmybaj 不正确",
    affiliationStatus: "历史创始成员；当前任职不按旧简介推断",
    userConfirmed: false,
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "Guodzh",
    name: "Guodong Zhang（张国栋）",
    categories: ["ai"],
    kind: "个人",
    topic: "训练、优化与生成模型",
    decision: "待确认",
    identityStatus: "已核对官网 / 本人链接",
    evidenceUrl: "https://www.cs.toronto.edu/~gdzhang/",
    evidenceNote: "2026-09-13 页面含 https://twitter.com/Guodzh。xAI 相关研究者；当前任职待复核",
    affiliationStatus: "xAI 相关研究者；当前任职待复核",
    userConfirmed: false,
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "TheGregYang",
    name: "Greg Yang",
    categories: ["ai"],
    kind: "个人",
    topic: "Tensor Programs 与模型训练理论",
    decision: "待确认",
    identityStatus: "已核对官网 / 本人链接",
    evidenceUrl: "https://thegregyang.com/",
    evidenceNote: "2026-09-13 页面含 https://twitter.com/TheGregYang/status/1501294412126560257。xAI 相关数学研究者；当前任职待复核",
    affiliationStatus: "xAI 相关数学研究者；当前任职待复核",
    userConfirmed: false,
    defaultWeight: 0.5,
    credibility: 52,
  }),
  xAccount({
    handle: "ZihangDai",
    name: "Zihang Dai",
    categories: ["ai"],
    kind: "个人",
    topic: "模型研究与 AI 编程",
    decision: "待确认",
    identityStatus: "公开账号候选；待进一步核验",
    evidenceUrl: "https://x.com/ZihangDai/with_replies",
    evidenceNote: "公开 X 页面索引显示 Zihang Dai 与 @ZihangDai；直连可间歇返回 403；GitHub 姓名一致，未找到直接反向社交链接",
    affiliationStatus: "xAI 相关研究者；当前任职待复核",
    userConfirmed: false,
    defaultWeight: 0.5,
    credibility: 52,
  }),
];

/** Case-insensitive handle set for duplicate detection and inventory checks. */
export const xAccountHandles: string[] = xAccountRegistry.map((entry) => entry.handle.toLowerCase());
